### ISSUE TITLE
Demo does not work.

### ISSUE THREAD

**Issue by salarmehr** [AminRahimi/angular-bootstrap-persian-datepicker#12]
The demo page does not work. It seems some files could not be loaded.

**Comment by AminRahimi** [comment]
no problem found
http://aminrahimi.github.io/angular-bootstrap-persian-datepicker/

**Comment by salarmehr** [comment]
It only works in FireFox (not in Opera,Chrome or IE)

**Comment by pooyadg** [comment]
دمو در فایرفاکس هم کارنمیکنه

**Comment by parid0kht** [comment]
@pooyadg از فیلتر شکن استفاده کنید کار میکنه

**Comment by morteza-gho** [comment]
Hi, demo is not working yet, solve the problem please

**Comment by amirtutunchi** [comment]
The Demo dose not working please solve this problem .

**Comment by AminRahimi** [comment]
problem solved
