### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by hamidzmi** [AminRahimi/angular-bootstrap-persian-datepicker#2]
Hi and thank you...
Please add usage in documention :)

**Comment by desmati** [comment]
واقعاً کار به درد بخوری کردی! ممنون.
فقط آقا مستندات خیلی ضعیفه!
چه اسکریپت ها و چه استایل هایی باید توی صفحه اینکولود بشن؟
پدرم دراومد تا از روی سمپل و با سعی و خطا تونستم راه بندازم.

**Comment by AminRahimi** [comment]
خوب الان شما میتونید زحمتش رو بکشید

**Comment by desmati** [comment]
چطوری؟
دو تا ایراد هم پیدا کردم. که نتونستم خودم برطرف کنم.
1- توی مد اینلاین وقتی روی ماه کلیک می کنی، ماه قبل رو به عنوان ماه جاری انتخاب کرده.
2- وقتی پارامتری که به عنوان مدل گذاشتیم رو مستقیم و بدون فیلتر توی صفحه بنویسیم، یعنی:
{{paramName}}
تاریخ یک روز قبل رو نشون میده
البته فکر کنم این به خاطر اینه که مقدار پارامتر  به صورت 
UTC 
هست درسته؟

**Comment by AminRahimi** [comment]
مورد یک حق با شماست
مورد دوم روتست کردم درست بود

**Comment by desmati** [comment]
نگفتید چطوری مستندات استفاده رو اضافه کنم؟
مورد دوم تاریخ و ساعتی که اعلام میکنه رو دقیق بررسی کنید.
تاریخ روز رو کلیک کنید و تست کنید لطفاً

**Comment by AminRahimi** [comment]
با فرمت رید می گیت باید بذارید
یا بدید به من بذارم
یا اینکه من به شما اکسس میدم خودتون پوش کنید

**Comment by desmati** [comment]
اگر امکان داره یه لینک آموزشی در مورد جیتهاب بده تا بتونم خودم پوش کنم.

**Comment by AminRahimi** [comment]
https://github.com/AminRahimi/angular-bootstrap-persian-datepicker/issues/5#issuecomment-70254399

**Comment by alireza-mokhtari** [comment]
As perfect as possible ...
You saved my neck about 3 days ...

**Comment by Lithium-HD** [comment]
این همه زحمت کشیده شده ولی نحوه استفاده معلوم نیست چطوریه!!!!

**Comment by navid-dada** [comment]
آقا لطف میکنین اگه یه 2 خط در مورد استفاده اش بنویسین 
من اگه بلد بودم تو stackoverflow اضافه میکردم . میذاشتمش اینجا

**Comment by navid-dada** [comment]
لطف میکنید اگه نحوه استفاده رو هم بگید.
من خودم قول میدم بذارمش تو داکیومنتا

**Comment by desmati** [comment]
آقا امین زحمت بکش اینو بذار توی ریدمی و یه مملکتی رو راحت کن:

## Requirements

- angularjs 1.x (tested with 1.5.6)
- angular-ui-bootstrap
- angular-ui-bootstrap-datepicker

## Installation

### Include following files in your page:

- angular.min.js
- dateparser.js
- position.js
- datepicker-tpls.js
- persiandate.js
- persian-datepicker-tpls.js

### Update your app definition:
```javascript
var app = angular.module('app',['ui.bootstrap.persian.datepicker','ui.bootstrap.datepicker']);
```
### Include the directive in your view:

#### Inline:
```html
<persian-datepicker ng-model="dt" min-date="minDate" show-weeks="true" class="well well-sm" starting-day="6"></persian-datepicker>
```

#### Popup:
```html
<p class="input-group">
                                            <input type="text" class="form-control" datepicker-popup-persian="{{format}}" ng-model="dt" is-open="persianIsOpen" datepicker-options="dateOptions" date-disabled="disabled(date, mode)" ng-required="true" close-text="بسته" />
                                            <span class="input-group-btn">
                                                <button type="button" class="btn btn-default" ng-click="openPersian($event)"><i class="glyphicon glyphicon-calendar"></i></button>
                                            </span>
                                        </p>
```

**Comment by desmati** [comment]
غلط املاییاشم بگیر ;)

**Comment by desmati** [comment]
[persian-datepicker-demo.zip](https://github.com/AminRahimi/angular-bootstrap-persian-datepicker/files/318188/persian-datepicker-demo.zip)
اینم پروژه دمو که از صفحه خودت ساختم

**Comment by desmati** [comment]
ضمناً نیازی به 
jquery
نیست. چرا توی پروژه اضافه کردی؟

**Comment by navid-dada** [comment]
یعنی یه مملکتی رو راحت کردی ها .... خدا خیرت بده


On Thu, Jun 16, 2016 at 3:01 PM, desmati <notifications@github.com> wrote:

> آقا امین زحمت بکش اینو بذار توی ریدمی و یه مملکتی رو راحت کن:
> Requirements
>
>    - angularjs 1.x (tested with 1.5.6)
>    - angular-ui-bootstrap
>    - angular-ui-bootstrap-datepicker
>
> Installation Include following files in your page:
>
>    - angular.min.js
>    - dateparser.js
>    - position.js
>    - datepicker-tpls.js
>    - persiandate.js
>    - persian-datepicker-tpls.js
>
> Update your app definition:
>
> var app = angular.module('app',['ui.bootstrap.persian.datepicker','ui.bootstrap.datepicker']);
>
> Include the directive in your view: Inline:
>
> <persian-datepicker ng-model="dt" min-date="minDate" show-weeks="true" class="well well-sm" starting-day="6"></persian-datepicker>
>
> Popup:
>
> <p class="input-group">
>                                             <input type="text" class="form-control" datepicker-popup-persian="{{format}}" ng-model="dt" is-open="persianIsOpen" datepicker-options="dateOptions" date-disabled="disabled(date, mode)" ng-required="true" close-text="بسته" />
>                                             <span class="input-group-btn">
>                                                 <button type="button" class="btn btn-default" ng-click="openPersian($event)"><i class="glyphicon glyphicon-calendar"></i></button>
>                                             </span>
>                                         </p>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/AminRahimi/angular-bootstrap-persian-datepicker/issues/2#issuecomment-226448351>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKF623GFhEukBqp5UHRJpUDWDARg3MWqks5qMSYQgaJpZM4CxDB4>
> .
>



-- 
Good Luck
Navid Shokri

**Comment by navid-dada** [comment]
آقا فقط
position.js 
چیه ؟؟؟

**Comment by desmati** [comment]
ui.bootstrap.position

**Comment by navid-dada** [comment]
آقا من نمیتونم 
popup
رو بالا بیارم.دایرکتیو
datepicker-popup-persian
را نمیشناسد

**Comment by AminRahimi** [comment]
باید انگولار یو آی بوت استرپ رو هم تو پروژه داشته باشید

**Comment by navid-dada** [comment]
this project is not updated with bootstrap ui v1.3.3 because $position and dateParser in new version have this names "$uibPosition" and "uibDateParser"

**Comment by desmati** [comment]
اینم یه دیت پیکر فارسی که الآن نوشتم و گذاشتم:
https://github.com/desmati/persian-angular-date-picker
شاید به دردتون خورد.
