### ISSUE TITLE
problem with using ui.bootstrap 1.3.3 and minDate option

### ISSUE THREAD

**Issue by ha0x7c7** [AminRahimi/angular-bootstrap-persian-datepicker#28]
When I want to use minDate option for date picker, it gives me error, this is link to plunk reproducing the issue.

http://plnkr.co/edit/ECgLrFmcJtYwTaxgzQQd?p=preview

**Comment by AminRahimi** [comment]
use min-date attr on directive element
      <input type="text" ng-model="dt2" datepicker-popup-persian is-open="isOpen2" min-date="options.minDate"  ng-click="isOpen2 = !isOpen2" />
